namespace DisabilityInPortal.Domain.Enums;

public enum ApplicationPropertyType
{
    None = 0,
    BeginApplication = 1,
    GeneralBusinessInformation = 2,
    LegalStructure = 3,
    FranchiseInformation = 4,
    HeadquartersInformation = 5,
    MailingAddressInformation = 6,
    PrimaryOwnerContactInformation = 7,
    CompanyContactInformation = 8,
    TrustDetails = 9,
    ContractorDetails = 10,
    TransportationDetails = 11,
    RealEstate = 12,
    Capabilities = 13,
    Owners = 14,
    DisabilityImpact = 15,
    EquipmentAndVehicle = 16,
    ManagementContributions = 17,
    ManagementResponsibilities = 18,
    DiversityDetails = 19,
    ContractReferenceDetails = 20,
    BankAndCreditReferenceDetails = 21,
    ManagementAtOutsideFirm = 22,
    AdditionalInformation = 23,
    AdditionalDocument = 24,
    BusinessRelationshipDetails = 25,
    FinancialSizeInformation = 26,
    ManagementChange = 27,
    Affidavit = 28,
    PaymentDetail = 29,
    Invoice = 30,
    ApplicationUser = 31
}