namespace DisabilityInPortal.Domain.Enums;

public enum DocumentType
{
    None = 0,
    FranchiseAgreement = 1,
    CertificationAgency = 2,
    RentalPurchaseAgreement = 3,
    LegalStructureGoverningDocument = 4,
    LicenseCertification = 5,
    ExecutedTrustDocumentation = 6,
    PictureId = 7,
    Passport = 8,
    EquipmentPurchaseAgreement = 9,
    VehiclePurchaseAgreement = 10,
    Resume = 11,
    SigningAuthority = 12,
    DiversityCertificate = 13,
    DisabilityImpact = 14,
    W2Or1099Form = 15,
    BankAndCreditReference = 16,
    Lawsuit = 17,
    Bankruptcy = 18,
    CertificationDenial = 19,
    SiteVisitAccomodationRequirements = 20,
    BusinessRelationshipDocument = 21,
    EmployeesList = 22,
    ProfitLossStatement = 23,
    BalanceSheet = 24,
    ManagementChange = 25,
    AdditionalDocument = 26,
    DefenceForm214 = 27,
    DisabilityRatingsLetter = 28,
    DisabilityStatement = 29,
    IndividualizedEducationProgram = 30,
    DisabilityBenefits = 31,
    DisabilityINPhysicianForm = 32,
    TransportationContract = 33,
    TransportationLease = 34,
    LoanAgreement = 35,
    ContractReference = 36,
    RecentItemizedPayRoll = 37,
    SsdStatement = 38,
    SsiStatement = 39,
    FederalTaxReturn = 40,
    VaVerificationLetter = 41
}